site_name: Grimwald Knowledge Base
site_description: A comprehensive knowledge base for Grimwald SMP
site_dir: built-docs
nav:
- Home: index.md
- ğŸ“š General Information:
  - "ğŸ“š Rules": rules.md
  - "ğŸ“š Roles": roles.md
  - "ğŸ“š Seasons": seasons.md
  - "ğŸ“š Events": events.md
  - "ğŸ“š Economy": economy.md
  - "ğŸ“š Donations": donations.md
- ğŸ›¡ï¸ Moderation:
  - "ğŸ›¡ï¸ Staff Guidelines": staff-guidelines.md
  - "ğŸ›¡ï¸ Commands and Permissions": commands.md
- ğŸ› ï¸ Server Management:
  - "ğŸ› ï¸ Setting Up": server-setup.md
  - "ğŸ› ï¸ Payments": payments.md
  - "ğŸ› ï¸ Plugins": plugins.md
  - "ğŸ› ï¸ Datapacks": datapacks.md
  - "ğŸ› ï¸ Preparing World Downloads": preparing-world-downloads.md
- ğŸŒ Website:
  - "ğŸŒ Updating the Website": website.md
  - "ğŸŒ Timeline": timeline.md
  - "ğŸŒ Stats": stats.md
- ğŸ«‚ Community:
  - "ğŸ«‚ Join Process": joining.md
  - "ğŸ«‚ Advertising": advertising.md
  - "ğŸ«‚ Brand Guidelines": branding.md
- ğŸ“œ Docs:
  - "ğŸ“œ Contributing": contributing.md
  - "ğŸ“œ Standards": standards.md
  - "ğŸ“œ Changelog": changelog.md

extra_css:
  - style.css